apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  params:
    - name: IMAGE
      description: Image description
      type: string
      default: "quay.io/tinlam/java-app"
    - name: TAG
      description: Preferred tag
      default: latest
  workspaces:
    - name: linked-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: linked-workspace
      params:
        - name: url
          value: https://github.com/aliabbas666/Java-maven-project1
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "false"
    - name: build-push-image
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: linked-workspace
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(params.TAG)"
        - name: CONTEXT
          value: "."
        - name: FORMAT
          value: "docker"
    - name: check-for-container-vulnerabilities
      taskRef:
        name: snyk-container
      params:
        - name: image
          value: quay.io/tinlam/java-app:latest
        - name: args
          value:
          - --severity-threshold=high
      runAfter:
        - build-push-image
      workspaces:
        - name: source
          workspace: linked-workspace
    - name: sonarqube-analysis
      taskRef:
        name: sonarqube-scanner
      params:
        - name: SONAR_HOST_URL
          value: https://sonarcloud.io
        - name: SONAR_PROJECT_KEY
          value: my-org-tekton_key
        - name: SONAR_ORGANIZATION
          value: my-org-tekton
        - name: SOURCE_TO_SCAN
          value: src
      runAfter:
        - build-push-image
      workspaces:
        - name: source
          workspace: linked-workspace
    - name: create-deployment
      taskRef:
        name: kubernetes-actions
      runAfter:
        - build-push-image
      params:
        - name: script
          value: |
            kubectl apply --filename deployment1.yaml
            kubectl apply --filename service.yaml
            kubectl apply --filename ingress.yaml
      workspaces:
        - name: manifest-dir
          workspace: linked-workspace
