apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0: https://quay.io/
type: kubernetes.io/basic-auth
stringData:
  username: tinlam
  password: Snoopy@007
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret1
  annotations:
    tekton.dev/docker-0: https://registry.redhat.io/
type: kubernetes.io/basic-auth
stringData:
  username: tinlam
  password: d545743D@007
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-login
secrets:
  - name: docker-secret
  - name: docker-secret1
