apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0: https://quay.io/
type: kubernetes.io/basic-auth
stringData:
  username: tinlam
  password: Snoopy@007
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret1
  annotations:
    tekton.dev/docker-0: https://registry.redhat.io/
type: kubernetes.io/basic-auth
stringData:
  username: tinlam
  password: d545743D@007
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/git-0: https://github.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: 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
  password: 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
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-login
secrets:
  - name: docker-secret
  - name: docker-secret1
  - name: basic-user-pass
  - name: snyk
  - name: snyk-monitor
