name: Check Environment

on:
  push:
    branches:
      - main

jobs:
  check-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Check Ubuntu Virtual Environment Provided by GitHub Action
        run: |
          lsb_release -a
          ip addr
          free -m
          lscpu
          df -h
          pwd
          date
      - name: Checkout Repository
        uses: actions/checkout@v3
