name: Run SonarQube Analysis

on:
  workflow_run:
    workflows: ["CI/CD Pipeline with Podman"]
    types:
      - completed

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_URL }}
        run: |
          export PATH=$PATH:/opt/sonar-scanner/bin
          sonar-scanner -Dsonar.projectKey=timlam007_Java-maven-project -Dsonar.java.binaries=target/classes -Dsonar.organization=timlam007 -Dsonar.sources=src -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
