name: Build Container

on:
  workflow_run:
    workflows: ["CI/CD Pipeline with Podman"]
    types:
      - completed

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          . /etc/os-release
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Login to Red Hat Registry
        run: |
          echo "Red Hat Registry Username: ${{ secrets.RH_REGISTRY_USERNAME }}"
          echo "Red Hat Registry Password: ${{ secrets.RH_REGISTRY_PASSWORD }}"
          podman login -u tinlam -p d545743D@007 registry.redhat.io
          podman login -u ${{ secrets.RH_REGISTRY_USERNAME }} -p ${{ secrets.RH_REGISTRY_PASSWORD }} quay.io

      - name: Build Podman Image
        run: podman build -t quay.io/tinlam/test/java-app:latest .

      - name: Push Podman Image
        run: podman push quay.io/tinlam/test/java-app:latest
