name: Deploy

on:
  workflow_run:
    workflows: ["CI/CD Pipeline with Podman"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install OpenShift CLI (oc)
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          chmod +x oc
          sudo mv oc /usr/local/bin/
          oc version

      - name: Set up OpenShift CLI
        run: |
          oc login --token=sha256~tLoCrtiLrPUKxQoe3DgLhfgPqBXKSySR1ILKvUB-2qA --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443

      - name: Apply OpenShift Manifests
        run: |
          oc apply -f deployment.yaml
          oc apply -f service.yaml
          oc apply -f route.yaml
