
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Maven Project
        run: mvn clean install

      - name: Run JUnit Tests
        run: mvn test
  build-container:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up podman
        uses: docker/setup-buildx-action@v1

      - name: Login to Red Hat Registry
        run: docker login -u ${{ secrets.RH_REGISTRY_USERNAME }} -p ${{ secrets.RH_REGISTRY_PASSWORD }} registry.redhat.io

      - name: Build Docker Image
        run: docker build -t java-app .
  scan-security-vulnerabilities:
   runs-on: ubuntu-latest
   needs: build-container

   steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Scan podman image 🐳
       uses: snyk/actions/docker@master
       continue-on-error: true
       with:
        image: java-app
  deploy:
    runs-on: ubuntu-latest
    needs: [scan-security-vulnerabilities]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenShift CLI (oc)
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          chmod +x oc
          sudo mv oc /usr/local/bin/
          oc version

      - name: Set up OpenShift CLI
        run: |
          oc login --token=sha256~EwJCLivWCr3oVkXMxj1vs3sfb7P4A_CYIunYxNHFSyY --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443

    
      - name: Apply OpenShift Manifests
        run: |
           pwd
           cd k8s
           oc apply -f .

      - name: Rollout Deployment
        run: oc rollout latest dc/java-app-deployment
