name: CI/CD Pipeline with mainPodman

on:
  push:
    branches:
      - main

jobs:
  check-environment:
    strategy:
      matrix:
        include:
          - file: '01-check-environment.yml'

    runs-on: ubuntu-latest
    steps:
      - name: Check Environment
        uses: ./.github/workflows/01-check-environment.yml

  build:
    strategy:
      matrix:
        include:
          - file: '02-build.yml'

    runs-on: ubuntu-latest
    needs: check-environment
    steps:
      - name: Build Maven Project
        uses: ./.github/workflows/02-build.yml

  sonarqube-analysis:
    strategy:
      matrix:
        include:
          - file: '03-sonarqube-analysis.yml'

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run SonarQube Analysis
        uses: ./.github/workflows/03-sonarqube-analysis.yml

  build-container:
    strategy:
      matrix:
        include:
          - file: '04-build-container.yml'

    runs-on: ubuntu-latest
    needs: sonarqube-analysis
    steps:
      - name: Build Container
        uses: ./.github/workflows/04-build-container.yml

  scan-security-vulnerabilities:
    strategy:
      matrix:
        include:
          - file: '05-scan-vulnerabilities.yml'

    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Scan Security Vulnerabilities
        uses: ./.github/workflows/05-scan-vulnerabilities.yml

  deploy:
    strategy:
      matrix:
        include:
          - file: '06-deploy.yml'

    runs-on: ubuntu-latest
    needs: scan-security-vulnerabilities
    steps:
      - name: Deploy
        uses: ./.github/workflows/06-deploy.yml
